# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 410)
        MainWindow.setMinimumSize(QtCore.QSize(384, 301))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.alarm_button = QtWidgets.QPushButton(self.centralWidget)
        self.alarm_button.setGeometry(QtCore.QRect(200, 285, 400, 60))
        self.alarm_button.setAutoFillBackground(False)
        self.alarm_button.setText("")
        self.alarm_button.setAutoDefault(False)
        self.alarm_button.setDefault(False)
        self.alarm_button.setFlat(False)
        self.alarm_button.setObjectName("alarm_button")
        self.time_label = QtWidgets.QLabel(self.centralWidget)
        self.time_label.setGeometry(QtCore.QRect(250, 210, 300, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(48)
        font.setItalic(False)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.temp_label = QtWidgets.QLabel(self.centralWidget)
        self.temp_label.setGeometry(QtCore.QRect(280, 20, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(48)
        self.temp_label.setFont(font)
        self.temp_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.temp_label.setObjectName("temp_label")
        self.weather_label = QtWidgets.QLabel(self.centralWidget)
        self.weather_label.setGeometry(QtCore.QRect(400, 50, 88, 80))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(48)
        self.weather_label.setFont(font)
        self.weather_label.setObjectName("weather_label")
        self.date_label = QtWidgets.QLabel(self.centralWidget)
        self.date_label.setGeometry(QtCore.QRect(260, 170, 270, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.date_label.setFont(font)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.location_label = QtWidgets.QLabel(self.centralWidget)
        self.location_label.setGeometry(QtCore.QRect(360, 30, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.location_label.setFont(font)
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        self.label_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_1.setGeometry(QtCore.QRect(700, 50, 44, 40))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(700, 100, 44, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(700, 150, 44, 40))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(700, 200, 44, 40))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(700, 250, 44, 40))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(700, 300, 44, 40))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(650, 50, 44, 40))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(650, 100, 44, 40))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(650, 150, 44, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(650, 200, 44, 40))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(650, 250, 44, 40))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(650, 300, 44, 40))
        self.label_12.setObjectName("label_12")
        self.comm_label = QtWidgets.QLabel(self.centralWidget)
        self.comm_label.setGeometry(QtCore.QRect(20, 65, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.comm_label.setFont(font)
        self.comm_label.setObjectName("comm_label")
        self.comm_icon = QtWidgets.QLabel(self.centralWidget)
        self.comm_icon.setGeometry(QtCore.QRect(60, 20, 80, 80))
        self.comm_icon.setObjectName("comm_icon")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(620, 20, 161, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.greeting_label = QtWidgets.QLabel(self.centralWidget)
        self.greeting_label.setGeometry(QtCore.QRect(260, 140, 270, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.greeting_label.setFont(font)
        self.greeting_label.setAlignment(QtCore.Qt.AlignCenter)
        self.greeting_label.setObjectName("greeting_label")
        self.alarm_button.raise_()
        self.time_label.raise_()
        self.weather_label.raise_()
        self.date_label.raise_()
        self.location_label.raise_()
        self.label_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.comm_label.raise_()
        self.comm_icon.raise_()
        self.label.raise_()
        self.greeting_label.raise_()
        self.temp_label.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "TextLabel"))
        self.temp_label.setText(_translate("MainWindow", "90"))
        self.weather_label.setText(_translate("MainWindow", "WeatherLabel"))
        self.date_label.setText(_translate("MainWindow", "TextLabel"))
        self.location_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.comm_label.setText(_translate("MainWindow", "comm_label"))
        self.comm_icon.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Your Weekly Forecast"))
        self.greeting_label.setText(_translate("MainWindow", "TextLabel"))


